[0.120s] Invoking command in '/lab2_ws/build/own_interfaces': CMAKE_PREFIX_PATH=/lab2_ws/install/lab_2:/opt/ros/galactic /usr/bin/cmake /lab2_ws/src/own_interfaces -DCMAKE_INSTALL_PREFIX=/lab2_ws/install/own_interfaces
[0.203s] -- Found rosidl_default_generators: 1.1.1 (/opt/ros/galactic/share/rosidl_default_generators/cmake)
[0.209s] -- Found ament_cmake_core: 1.1.4 (/opt/ros/galactic/share/ament_cmake_core/cmake)
[0.267s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.487s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.508s] -- Found rosidl_adapter: 2.2.1 (/opt/ros/galactic/share/rosidl_adapter/cmake)
[1.018s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.186s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[1.832s] CMake Error at /opt/ros/galactic/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[1.833s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.834s]   own_interfaces --arguments-file
[1.834s]   /lab2_ws/build/own_interfaces/rosidl_adapter__arguments__own_interfaces.json
[1.834s]   --output-dir /lab2_ws/build/own_interfaces/rosidl_adapter/own_interfaces
[1.834s]   --output-file
[1.834s]   /lab2_ws/build/own_interfaces/rosidl_adapter/own_interfaces.idls) returned
[1.840s]   error code 1:
[1.840s] 
[1.840s]   Traceback (most recent call last):
[1.840s] 
[1.840s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.841s]       return _run_code(code, main_globals, None,
[1.841s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1.841s]       exec(code, run_globals)
[1.841s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.841s]       sys.exit(main())
[1.841s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[1.841s]       abs_idl_file = convert_to_idl(
[1.841s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[1.842s]       return convert_srv_to_idl(
[1.842s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[1.842s]       srv = parse_service_string(package_name, input_file.stem, content)
[1.842s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 852, in parse_service_string
[1.842s]       request_message = parse_message_string(
[1.843s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
[1.843s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[1.843s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
[1.843s]       self.base_type = BaseType(
[1.843s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[1.843s]       raise InvalidResourceName(
[1.843s] 
[1.843s]   rosidl_adapter.parser.InvalidResourceName: 'RPM_Interface_Request' is an
[1.844s]   invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.844s] 
[1.844s] Call Stack (most recent call first):
[1.844s]   /opt/ros/galactic/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.844s]   CMakeLists.txt:10 (rosidl_generate_interfaces)
[1.844s] 
[1.844s] 
[1.855s] -- Configuring incomplete, errors occurred!
[1.855s] See also "/lab2_ws/build/own_interfaces/CMakeFiles/CMakeOutput.log".
[1.869s] Invoked command in '/lab2_ws/build/own_interfaces' returned '1': CMAKE_PREFIX_PATH=/lab2_ws/install/lab_2:/opt/ros/galactic /usr/bin/cmake /lab2_ws/src/own_interfaces -DCMAKE_INSTALL_PREFIX=/lab2_ws/install/own_interfaces
